<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H0PI4DT" failures="1" tests="5" name="restAPIExample.TC_002_POST_CreateUser" time="5.548" errors="0" timestamp="2022-01-13T12:43:07 IST" skipped="4">
  <testcase classname="restAPIExample.TC_002_POST_CreateUser" name="getUserDetailsTest" time="5.548">
    <failure message="expected [200] but found [201]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [201]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at restAPIExample.TC_002_POST_CreateUser.getUserDetailsTest(TC_002_POST_CreateUser.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getUserDetailsTest -->
  <system-out/>
  <testcase classname="restAPIExample.TC_002_POST_CreateUser" name="verifyStatusCode" time="0.000">
    <skipped/>
  </testcase> <!-- verifyStatusCode -->
  <system-out/>
  <testcase classname="restAPIExample.TC_002_POST_CreateUser" name="verifyHeaderContentType" time="0.000">
    <skipped/>
  </testcase> <!-- verifyHeaderContentType -->
  <system-out/>
  <testcase classname="restAPIExample.TC_002_POST_CreateUser" name="verifyResponseTime" time="0.000">
    <skipped/>
  </testcase> <!-- verifyResponseTime -->
  <system-out/>
  <testcase classname="restAPIExample.TC_002_POST_CreateUser" name="verifyStatusLine" time="0.000">
    <skipped/>
  </testcase> <!-- verifyStatusLine -->
  <system-out/>
</testsuite> <!-- restAPIExample.TC_002_POST_CreateUser -->
